### ISSUE TITLE
why timeout when I change channals trigger goroutine to normal function

### ISSUE THREAD

**Issue by ai-chen2050** [nshafer/phx#3]
why will timeout when I change channels trigger the goroutine to normal function?  because so many goroutines will be created.

<img width="1111" alt="image" src="https://user-images.githubusercontent.com/27693952/205849348-a52a5ebc-10da-4408-aa61-5a334e288746.png">

<img width="1331" alt="image" src="https://user-images.githubusercontent.com/27693952/205849662-c6030bcd-4686-46e9-8f45-aee5af93e49a.png">

**Comment by ai-chen2050** [comment]
@nshafer can you provide limits message  callback goroutine ?

**Comment by nshafer** [comment]
Spawning goroutines is relatively cheap, and I do this so that if you have expensive code when handling a message, it does not block the main receiver goroutine. This is similar to how net/http creates a new goroutine for every incoming request.

I do not understand your second question, "can you provide limits message callback goroutine ?" Can you open a new Issue and rephrase?
